
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_app
    username: root
    password: admin123
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
#  main:
#    allow-circular-references: true